name: "Unit Tests"

on:
  workflow_dispatch:
  pull_request:

permissions:
  contents: write

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Plugin repo
      uses: actions/checkout@v4

    - name: Set Up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
        check-latest: true

    - name: Run Tests
      run: |
        set -ex
        export GOPATH=$PWD/gopath
        export PATH=$GOPATH/bin:$PATH

        BINARY_VALIDATION=false bin/test

